# Generated by Django 3.1.4 on 2021-01-03 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_player_puzzleselection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puzzleselection',
            options={'ordering': ['sort_key']},
        ),
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'Started'), (3, 'Ended')], default=1),
        ),
        migrations.AddField(
            model_name='puzzleselection',
            name='sort_key',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='PlayerGuess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
                ('puzzle_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.puzzleselection')),
            ],
            options={
                'verbose_name_plural': 'Player guesses',
            },
        ),
    ]
