# Generated by Django 3.1.5 on 2021-01-10 11:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playerguess',
            name='puzzle_selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='game.puzzleselection'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='photo',
            field=models.ImageField(upload_to=game.models.upload_location),
        ),
        migrations.AlterField(
            model_name='puzzleselection',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected', to='game.game'),
        ),
    ]
