# Generated by Django 3.1.5 on 2021-02-14 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_order_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='name',
        ),
        migrations.AddField(
            model_name='game',
            name='code',
            field=models.CharField(default='-----', max_length=5),
        ),
        migrations.AlterField(
            model_name='correctanswer',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='game.puzzle'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(condition=models.Q(state=1), fields=('code',), name='unique_code_game'),
        ),
    ]
